# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  build:

    runs-on: ubuntu-latest

    if: github.actor == github.event.repository.owner.login  
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    # Basic test
    - name: Basic Test
      run: |
        npm install
        bash <(curl -s https://codecov.io/bash)
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


    # Basic test
    - name: Basic Test
      run: |
        npm restart
        npm test
        bash <(curl -s https://codecov.io/bash)
      env:
        CI: true
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}




